export const OpenClawErrorCodes = {
  // Gateway and protocol
  NOT_LINKED: "NOT_LINKED",
  NOT_PAIRED: "NOT_PAIRED",
  AGENT_TIMEOUT: "AGENT_TIMEOUT",
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAVAILABLE: "UNAVAILABLE",
  GATEWAY_CONNECTION_FAILED: "GATEWAY_CONNECTION_FAILED",
  GATEWAY_PARSE_FAILED: "GATEWAY_PARSE_FAILED",
  GATEWAY_REQUEST_FAILED: "GATEWAY_REQUEST_FAILED",
  GATEWAY_RESPONSE_INVALID: "GATEWAY_RESPONSE_INVALID",

  // Memory
  MEMORY_VECTOR_UNAVAILABLE: "MEMORY_VECTOR_UNAVAILABLE",
  MEMORY_EMBEDDING_FAILED: "MEMORY_EMBEDDING_FAILED",
  MEMORY_INDEX_FAILED: "MEMORY_INDEX_FAILED",
  MEMORY_QUERY_FAILED: "MEMORY_QUERY_FAILED",
  MEMORY_PERSIST_FAILED: "MEMORY_PERSIST_FAILED",

  // Channels
  CHANNEL_SEND_FAILED: "CHANNEL_SEND_FAILED",
  CHANNEL_CONNECTION_LOST: "CHANNEL_CONNECTION_LOST",
  CHANNEL_AUTH_FAILED: "CHANNEL_AUTH_FAILED",
  CHANNEL_RATE_LIMITED: "CHANNEL_RATE_LIMITED",
  CHANNEL_TIMEOUT: "CHANNEL_TIMEOUT",

  // Tools
  TOOL_EXECUTION_FAILED: "TOOL_EXECUTION_FAILED",
  TOOL_TIMEOUT: "TOOL_TIMEOUT",
  TOOL_VALIDATION_FAILED: "TOOL_VALIDATION_FAILED",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",

  // Plugins
  PLUGIN_LOAD_FAILED: "PLUGIN_LOAD_FAILED",
  PLUGIN_HOOK_FAILED: "PLUGIN_HOOK_FAILED",
  PLUGIN_VALIDATION_FAILED: "PLUGIN_VALIDATION_FAILED",
  PLUGIN_UNSUPPORTED: "PLUGIN_UNSUPPORTED",

  // Configuration
  CONFIG_VALIDATION_FAILED: "CONFIG_VALIDATION_FAILED",
  CONFIG_LOAD_FAILED: "CONFIG_LOAD_FAILED",
  CONFIG_SAVE_FAILED: "CONFIG_SAVE_FAILED",
  CONFIG_MISSING_REQUIRED: "CONFIG_MISSING_REQUIRED",

  // Browser
  BROWSER_LAUNCH_FAILED: "BROWSER_LAUNCH_FAILED",
  BROWSER_NAVIGATION_FAILED: "BROWSER_NAVIGATION_FAILED",
  BROWSER_TIMEOUT: "BROWSER_TIMEOUT",

  // Agent
  AGENT_BILLING_ERROR: "AGENT_BILLING_ERROR",

  // Generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type OpenClawErrorCode = (typeof OpenClawErrorCodes)[keyof typeof OpenClawErrorCodes];
